### PR TITLE
Adding Nokogiri Fast adapter and fix travis setup

### PR DESCRIPTION
**Pull request by bragboy**
Premailer right now has three adapters namely hpricot, nokogiri and nokogumbo. As for the adapters themselves, they work fine, however, the performance of all the adapters are very slow in terms of running time.

We've earlier raised this issue - #317. We also tried the solution proposed by @akzhan on improving the performance, however, the slowness is not with the libraries used, however with the Algorithm that was being used to search the document. In some pathological cases, when the email DOM element is really large especially when we are using tables to support responsiveness across email clients. Because of this, it takes 400-500 seconds just to inline the styles. Even for smaller DOM cases, the time taken is more than 10 seconds which in computing terms, is years.

So we have tuned the Algorithm by using a proactive indexing technique. We earlier thought of overriding the existing nokogiri adapter, but then that may interfere with other users who are using the existing nokogori adapter by default. That is the reason, I wrote a new adapter called NokogiriFast which does not intrude with the existing users of the premailer gem.

After this patch, the time has reduced a lot by 20x! Which means the earlier time of 500 seconds got reduced to 20 seconds and the ones that use to take 10 seconds are now rendering in half a second.

I've also fixed the long failing Travis choke along with this. I had to tweak few library versions in order to get this up and running. As for the spec failures indicated, they are even failing before I added my feature.

Once this pull request is accepted and a new gem version released, I will create a PR against the premailer_rails gem.

Let me know if you have any feedback/questions on this PR, I will be more than happy to address/explain.

### CODE REVIEW

**Comment by akzhan** [comment]
Thanks a lot, just released as 1.9.0

**Comment by akzhan** [comment]
@bragboy can I add You to our `premailer` team?

**Comment by bragboy** [comment]
@akzhan - Please add me! thanks

**Comment by akzhan** [comment]
I was added you to team. feel free to contribute and review code as evolutioner.

**Comment by bragboy** [comment]
Thanks @akzhan sure!

**Pull request merged**
