### PR TITLE
Fix plaintext bug for links with single quote marks in the URI (#375)

### LINKED ISSUE #375: In plaintext version, links that include a single quote are truncated
For example:

```html
<a href="https://en.wikipedia.org/wiki/King's_Gambit">King's Gambit</a>
```
outputs
```
"King's Gambit ( https://en.wikipedia.org/wiki/King )"
```

### PR DESCRIPTION
**Pull request by ragesoss**
The link regex was matching on either single or double quotes to detect the start/end of an href, so an href that includes a single quote mark as part if the link were not being captured correctly.

This tweaks the link substitution to treat links with single quotes independently from those with double quotes, so that the URIs such as https://en.wikipedia.org/wiki/King's_Gambit are handled correctly.

Fixes  #375

### CODE REVIEW

**Comment by ragesoss** [comment]
Note: The tests are passing for this when the tests are run with a fixed seed. I'm not adding the seed in this PR, since it looks like #370 will fix the build without requiring a seed.

**Comment by meowsus** [comment]
@grosser this looks good to me, but we might have to update Travis to include the 2.5 and 2.6 jobs before rerunning this branch's builds?

**Comment by grosser** [comment]
I doubt it will break anything ... so I'd just merge.
Can also do the manual merge and run tests locally to verify 🤷‍♂

**Comment by meowsus** [comment]
@grosser I merged and ran the tests locally. Everything passed so this has been merged.

Thanks for your contribution @ragesoss!

**Pull request closed without merging**
