### PR TITLE
bump htmlentities to 4.3.3

### PR DESCRIPTION
**Pull request by BenMorganIO**
This removes a warning from ruby 2.2.

### CODE REVIEW

**Comment by leifcr** [comment]
@BenMorganIO I was just about to do a similar PR :+1: 
https://github.com/leifcr/premailer/commit/66caf7348ed42d702a491429d86f855c213a54a3

I suggest removing upper requirement and require >=4.0.0 of htmlentities?

**Comment by BenMorganIO** [comment]
@leifcr I think that's a great idea.

**Comment by colszowka** [comment]
+1 on shipping a release. By means of https://github.com/threedaymonk/htmlentities/pull/17 this is fixed in htmlentities, but I get this warning every single time I run anything on my rails app because of premailers strictness.

**Comment by BenMorganIO** [comment]
bump

**Comment by akzhan** [comment]
released

**Pull request merged**
