### PR TITLE
Fix script removal in plain text conversion

### PR DESCRIPTION
**Pull request by meowsus**
This pays special attention to script tags, by removing them wholesale. This branch also contains @mlandauer's work to fix the build (#370).

### CODE REVIEW

**Comment by meowsus** [comment]
@ndbroadbent Is there something I can do to get this moved along?

**Comment by ndbroadbent** [comment]
Hey, sorry I’m not involved with premailer maintenance anymore, and I’m not currently using it any projects.

I took a very quick look but I don’t really understand the changes too much, and unfortunately I don’t have enough time or energy to review and test these changes thoroughly and release a new version.

I’m not sure who has admin permissions for the repo, but it would be great if you could be added as a maintainer since you are actively using the gem, then you could keep an eye on any issues after merging in the PR.

**Comment by meowsus** [comment]
No problemo @ndbroadbent. Thanks for your response!

> I took a very quick look but I don’t really understand the changes too much...

To clarify, the build was breaking, so to get it passing I brought in @mlandauer's branch (#370) into my branch to fix it. This way I was able to more reliably test the application while I was making changes.

Then my fix is to strip <script> tags out of the generated text versions of the emails. Any included script was showing up in plain-text in these versions, which isn't what we would want.

Perhaps @alexdunae may know who I should talk to about becoming a maintainer?

**Comment by grosser** [comment]
plz rebase

**Comment by grosser** [comment]
I added @meowsus as collaborator ... need to talk to @alexdunae to get gem access though https://rubygems.org/gems/premailer

**Comment by meowsus** [comment]
Ah, thank you @grosser! I've rebased my branch against premailer:master.

**Pull request merged**
